[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed  = 115200
build_flags   = -Iinclude

lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.0
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    knolleary/PubSubClient @ ^2.8.0

[env:enroll]
extends = common

upload_protocol = espota
upload_port = 192.168.68.138      
upload_flags =
    --port=3232
    --auth=ota_password

build_src_filter =
    +<modules/>
    +<enroll/>
build_flags =
    ${common.build_flags}
    -D OTA_HOSTNAME=\"ESP32-Timely-Enroll\"
    -D OTA_PASSWORD=\"ota_password\"

[env:scan]
extends = common

upload_protocol = espota
upload_port = 192.168.68.138      
upload_flags =
    --port=3232
    --auth=ota_password

build_src_filter =
    +<modules/>
    +<scan/>
build_flags =
    ${common.build_flags}
    -D OTA_HOSTNAME=\"ESP32-Timely-Scan\"
    -D OTA_PASSWORD=\"ota_password\"

[env:test]
extends = common

upload_protocol = espota
upload_port = 192.168.68.138      
upload_flags =
    --port=3232
    --auth=ota_password

build_src_filter =
    +<test/>
build_flags =
    ${common.build_flags}
    -D OTA_HOSTNAME=\"ESP32-Timely-Test\"
    -D OTA_PASSWORD=\"ota_password\"