[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed  = 115200
build_flags   = -Iinclude

lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library @ ^2.1.0
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    knolleary/PubSubClient @ ^2.8.0

[env:enroll]
extends = common
build_src_filter =
    +<modules/>
    +<enroll/>

[env:scan]
extends = common
build_src_filter =
    +<modules/>
    +<scan/>

[env:test]
extends = common
build_src_filter =
    +<modules/>
    +<test/>